#!/usr/bin/env bash
# Install Nginx on server
# Set server to listen to port 80
# On GET request display "Holberton School"
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
