#!/usr/bin/env bash
# Install Nginx on server
# Set server to listen to port 80
# On GET request display "Holberton School"
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
