#!/usr/bin/env bash
# Install Nginx on server
# Set server to listen to port 80
# On GET request display "Holberton School"
# Redirect on /redirect_me
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;\n' /etc/nginx/sites-available/default
sudo service nginx restart
