#!/usr/bin/env bash
# Install server, create 404 html file, set redirect and set new 404 page
apt-get -y update
apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/new_404.html
sudo sed -i '/server_name _/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n}' /etc/nginx/sites-available/default
sudo sed -i '/server_name _/a \terror_page 404 /new_404.html; \nlocation = /new_404.html \n{\n\troot /var/www/html/;\n\tinternal; \n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
