#!/usr/bin/env bash
# This script pings the ip given as argument to the program
# Pings it 5 times
# If there is no argument given it will print an error message
i="0"
PID=$$
if [ $# -ne 1 ]
then
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	ping -c 5 $1
fi
