#!/usr/bin/env bash
# this script does a lot of stuff
trap "echo \"I hate the kill command\"" SIGTERM
trap "echo \"Y U no love me?!\"" SIGINT
echo "$$" > /var/run/holbertonscript.pid
while true; do
      echo "To infinity and beyond"
done
trap "rm -rf /var/run/holbertonscript.pid && pkill -f \"100-process_and_pid_file\"" SIGQUIT
trap "rm -rf /var/run/holbertonscript.pid && pkill -f \"100-process_and_pid_file\"" SIGTERM
