#!/usr/bin/env bash
# this script prints numbers from 1 to 20.
#+ in case of 4, 9 and 17 prints extra text
i="1"
while [ $i -le 20 ]; do
      echo $i
      case $i in
	  4)
	      echo "bad luck from China" ;;
	  9)
	      echo "bad luck from Japan" ;;
	  17)
	      echo "bad luck from Italy" ;;
      esac
      i=$((i+1))
done
