#!/usr/bin/env bash
# This script changes localhost to 127.0.0.2
# add facebook to 8.8.8.8 instead of original
sed 's/127.0.0.1/127.0.0.2/' -i /etc/hosts
sed '$ a 8.8.8.8\tfacebook.com' -i /etc/hosts
