#!/usr/bin/env bash
# Configures the server to listen incoming traffic from port 8080 and runs nginx as nginx user
pkill apache2
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
